AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.handler
      Runtime: python3.12
      Timeout: 30
      Environment:
        Variables:
          GEMINI_API_KEY: "" # Deixar vazio, será sobrescrito pelo env.json
      Events:
        LambdaEnglishCorrector:
          Type: HttpApi
          Properties:
            Path: /corrector
            Method: POST
